import { Menu, TipoDeProducto } from "../interfaces";

export const validProductType: TipoDeProducto[] = [
  "Paste Dulce",
  "Paste Salado",
  "Otros",
  "Paste Mini Dulce",
  "Paste Mini Salado",
  "Paste Empleado Dulce",
  "Paste Empleado Salado",
];

export const validMenuProducts: Menu[] = [
  // Pastes dulces
  {
    _id: "PD_ACL",
    saborDelPaste: "Arroz con leche",
    precio: 30,
    tipoDeProducto: "Paste Dulce",
  },
  {
    _id: "PD_CP",
    saborDelPaste: "Crema pastelera",
    precio: 30,
    tipoDeProducto: "Paste Dulce",
  },
  {
    _id: "PD_FCP",
    saborDelPaste: "Frambuesa con philadelphia",
    precio: 30,
    tipoDeProducto: "Paste Dulce",
  },
  {
    _id: "PD_FRCP",
    saborDelPaste: "Frutos rojos con philadelphia",
    precio: 30,
    tipoDeProducto: "Paste Dulce",
  },
  {
    _id: "PD_GCP",
    saborDelPaste: "Guayaba con philadelphia",
    precio: 30,
    tipoDeProducto: "Paste Dulce",
  },
  {
    _id: "PD_H",
    saborDelPaste: "Hawaiano",
    precio: 30,
    tipoDeProducto: "Paste Dulce",
  },
  {
    _id: "PD_MCP",
    saborDelPaste: "Manzana con philadelphia",
    precio: 30,
    tipoDeProducto: "Paste Dulce",
  },
  {
    _id: "PD_NCP",
    saborDelPaste: "Nutella con philadelphia",
    precio: 30,
    tipoDeProducto: "Paste Dulce",
  },
  {
    _id: "PD_PCP",
    saborDelPaste: "Piña con philadelphia",
    precio: 30,
    tipoDeProducto: "Paste Dulce",
  },
  // Pastes salados
  {
    _id: "PS_A",
    saborDelPaste: "Atun",
    precio: 30,
    tipoDeProducto: "Paste Salado",
  },
  {
    _id: "PS_FCC",
    saborDelPaste: "Frijol con chorizo",
    precio: 30,
    tipoDeProducto: "Paste Salado",
  },
  {
    _id: "PS_H",
    saborDelPaste: "Hidalguense",
    precio: 30,
    tipoDeProducto: "Paste Salado",
  },
  {
    _id: "PS_M",
    saborDelPaste: "Marlin",
    precio: 30,
    tipoDeProducto: "Paste Salado",
  },
  {
    _id: "PS_MR",
    saborDelPaste: "Mole rojo",
    precio: 30,
    tipoDeProducto: "Paste Salado",
  },
  {
    _id: "PS_MV",
    saborDelPaste: "Mole Verde",
    precio: 30,
    tipoDeProducto: "Paste Salado",
  },
  {
    _id: "PS_PCC",
    saborDelPaste: "Papa con carne",
    precio: 30,
    tipoDeProducto: "Paste Salado",
  },
  {
    _id: "PS_PP",
    saborDelPaste: "Pepperoni",
    precio: 30,
    tipoDeProducto: "Paste Salado",
  },
  {
    _id: "PS_RCC",
    saborDelPaste: "Rajas con champiñon",
    precio: 30,
    tipoDeProducto: "Paste Salado",
  },
  {
    _id: "PS_ECR",
    saborDelPaste: "Espinacas con requeson",
    precio: 30,
    tipoDeProducto: "Paste Salado",
  },
  {
    _id: "PS_S",
    saborDelPaste: "Salchicha",
    precio: 30,
    tipoDeProducto: "Paste Salado",
  },
  {
    _id: "PS_TCP",
    saborDelPaste: "Tocino con papas",
    precio: 30,
    tipoDeProducto: "Paste Salado",
  },
  {
    _id: "PS_P",
    saborDelPaste: "Pastor",
    precio: 30,
    tipoDeProducto: "Paste Salado",
  },
  {
    _id: "PS_T",
    saborDelPaste: "Tapatio",
    precio: 30,
    tipoDeProducto: "Paste Salado",
  },
  {
    _id: "PS_C",
    saborDelPaste: "Choriqueso",
    precio: 30,
    tipoDeProducto: "Paste Salado",
  },
  // Otros
  {
    _id: "O_AN",
    saborDelPaste: "Agua natural",
    precio: 10,
    tipoDeProducto: "Otros",
  },
  {
    _id: "O_CC",
    saborDelPaste: "Café chico",
    precio: 25,
    tipoDeProducto: "Otros",
  },
  {
    _id: "O_C12O",
    saborDelPaste: "Café 12 Onz",
    precio: 30,
    tipoDeProducto: "Otros",
  },
  {
    _id: "O_C16O",
    saborDelPaste: "Café 16 Onz",
    precio: 35,
    tipoDeProducto: "Otros",
  },
  {
    _id: "O_G",
    saborDelPaste: "Galletas",
    precio: 20,
    tipoDeProducto: "Otros",
  },
  {
    _id: "O_GCC",
    saborDelPaste: "Galletas caja chica",
    precio: 60,
    tipoDeProducto: "Otros",
  },
  {
    _id: "O_GCG",
    saborDelPaste: "Galletas caja grande",
    precio: 70,
    tipoDeProducto: "Otros",
  },
  {
    _id: "O_CCCT",
    saborDelPaste: "Coca cola con taparrosca",
    precio: 20,
    tipoDeProducto: "Otros",
  },
  {
    _id: "O_CCDL",
    saborDelPaste: "Coca cola de lata",
    precio: 20,
    tipoDeProducto: "Otros",
  },
  {
    _id: "O_CCDLL",
    saborDelPaste: "Coca cola de lata light",
    precio: 20,
    tipoDeProducto: "Otros",
  },
  {
    _id: "O_AM",
    saborDelPaste: "Agua mineral",
    precio: 20,
    tipoDeProducto: "Otros",
  },
  {
    _id: "O_FT",
    saborDelPaste: "Fuze tea",
    precio: 20,
    tipoDeProducto: "Otros",
  },
  {
    _id: "O_S",
    saborDelPaste: "Sprite",
    precio: 20,
    tipoDeProducto: "Otros",
  },
  {
    _id: "O_F",
    saborDelPaste: "Fanta",
    precio: 20,
    tipoDeProducto: "Otros",
  },
  {
    _id: "O_M",
    saborDelPaste: "Mundet",
    precio: 20,
    tipoDeProducto: "Otros",
  },
  {
    _id: "O_J",
    saborDelPaste: "Jarritos",
    precio: 20,
    tipoDeProducto: "Otros",
  },
  {
    _id: "O_P4M",
    saborDelPaste: "Pepsi 400 ml",
    precio: 10,
    tipoDeProducto: "Otros",
  },
  {
    _id: "O_CCSA",
    saborDelPaste: "Coca cola sin azucar",
    precio: 15,
    tipoDeProducto: "Otros",
  },
  {
    _id: "O_JX",
    saborDelPaste: "Jumex",
    precio: 12,
    tipoDeProducto: "Otros",
  },
  {
    _id: "O_SR",
    saborDelPaste: "Salsa roja",
    precio: 5,
    tipoDeProducto: "Otros",
  },
  {
    _id: "O_SV",
    saborDelPaste: "Salsa verde",
    precio: 5,
    tipoDeProducto: "Otros",
  },
  // Pastes minis dulces
  {
    _id: "PMD_ACL",
    saborDelPaste: "Arroz con leche",
    precio: 18,
    tipoDeProducto: "Paste Mini Dulce",
  },
  {
    _id: "PMD_CP",
    saborDelPaste: "Crema pastelera",
    precio: 18,
    tipoDeProducto: "Paste Mini Dulce",
  },
  {
    _id: "PMD_FCP",
    saborDelPaste: "Frambuesa con philadelphia",
    precio: 18,
    tipoDeProducto: "Paste Mini Dulce",
  },
  {
    _id: "PMD_FRCP",
    saborDelPaste: "Frutos rojos con philadelphia",
    precio: 18,
    tipoDeProducto: "Paste Mini Dulce",
  },
  {
    _id: "PMD_GCP",
    saborDelPaste: "Guayaba con philadelphia",
    precio: 18,
    tipoDeProducto: "Paste Mini Dulce",
  },
  {
    _id: "PMD_H",
    saborDelPaste: "Hawaiano",
    precio: 18,
    tipoDeProducto: "Paste Mini Dulce",
  },
  {
    _id: "PMD_MCP",
    saborDelPaste: "Manzana con philadelphia",
    precio: 18,
    tipoDeProducto: "Paste Mini Dulce",
  },
  {
    _id: "PMD_NCP",
    saborDelPaste: "Nutella con philadelphia",
    precio: 18,
    tipoDeProducto: "Paste Mini Dulce",
  },
  {
    _id: "PMD_PCP",
    saborDelPaste: "Piña con philadelphia",
    precio: 18,
    tipoDeProducto: "Paste Mini Dulce",
  },
  // Pastes minis salados
  {
    _id: "PMS_A",
    saborDelPaste: "Atun",
    precio: 18,
    tipoDeProducto: "Paste Mini Salado",
  },
  {
    _id: "PMS_FCC",
    saborDelPaste: "Frijol con chorizo",
    precio: 18,
    tipoDeProducto: "Paste Mini Salado",
  },
  {
    _id: "PMS_H",
    saborDelPaste: "Hidalguense",
    precio: 18,
    tipoDeProducto: "Paste Mini Salado",
  },
  {
    _id: "PMS_M",
    saborDelPaste: "Marlin",
    precio: 18,
    tipoDeProducto: "Paste Mini Salado",
  },
  {
    _id: "PMS_MR",
    saborDelPaste: "Mole rojo",
    precio: 18,
    tipoDeProducto: "Paste Mini Salado",
  },
  {
    _id: "PMS_MV",
    saborDelPaste: "Mole Verde",
    precio: 18,
    tipoDeProducto: "Paste Mini Salado",
  },
  {
    _id: "PMS_PCC",
    saborDelPaste: "Papa con carne",
    precio: 18,
    tipoDeProducto: "Paste Mini Salado",
  },
  {
    _id: "PMS_PP",
    saborDelPaste: "Pepperoni",
    precio: 18,
    tipoDeProducto: "Paste Mini Salado",
  },
  {
    _id: "PMS_RCC",
    saborDelPaste: "Rajas con champiñon",
    precio: 18,
    tipoDeProducto: "Paste Mini Salado",
  },
  {
    _id: "PMS_ECR",
    saborDelPaste: "Espinacas con requeson",
    precio: 18,
    tipoDeProducto: "Paste Mini Salado",
  },
  {
    _id: "PMS_S",
    saborDelPaste: "Salchicha",
    precio: 18,
    tipoDeProducto: "Paste Mini Salado",
  },
  {
    _id: "PMS_TCP",
    saborDelPaste: "Tocino con papas",
    precio: 18,
    tipoDeProducto: "Paste Mini Salado",
  },
  {
    _id: "PMS_P",
    saborDelPaste: "Pastor",
    precio: 18,
    tipoDeProducto: "Paste Mini Salado",
  },
  {
    _id: "PMS_T",
    saborDelPaste: "Tapatio",
    precio: 18,
    tipoDeProducto: "Paste Mini Salado",
  },
  {
    _id: "PMS_C",
    saborDelPaste: "Choriqueso",
    precio: 18,
    tipoDeProducto: "Paste Mini Salado",
  },
  // Pastes empleados dulces
  {
    _id: "PED_ACL",
    saborDelPaste: "Arroz con leche",
    precio: 25,
    tipoDeProducto: "Paste Empleado Dulce",
  },
  {
    _id: "PED_CP",
    saborDelPaste: "Crema pastelera",
    precio: 25,
    tipoDeProducto: "Paste Empleado Dulce",
  },
  {
    _id: "PED_FCP",
    saborDelPaste: "Frambuesa con philadelphia",
    precio: 25,
    tipoDeProducto: "Paste Empleado Dulce",
  },
  {
    _id: "PED_FRCP",
    saborDelPaste: "Frutos rojos con philadelphia",
    precio: 25,
    tipoDeProducto: "Paste Empleado Dulce",
  },
  {
    _id: "PED_GCP",
    saborDelPaste: "Guayaba con philadelphia",
    precio: 25,
    tipoDeProducto: "Paste Empleado Dulce",
  },
  {
    _id: "PED_H",
    saborDelPaste: "Hawaiano",
    precio: 25,
    tipoDeProducto: "Paste Empleado Dulce",
  },
  {
    _id: "PED_MCP",
    saborDelPaste: "Manzana con philadelphia",
    precio: 25,
    tipoDeProducto: "Paste Empleado Dulce",
  },
  {
    _id: "PED_NCP",
    saborDelPaste: "Nutella con philadelphia",
    precio: 25,
    tipoDeProducto: "Paste Empleado Dulce",
  },
  {
    _id: "PED_PCP",
    saborDelPaste: "Piña con philadelphia",
    precio: 25,
    tipoDeProducto: "Paste Empleado Dulce",
  },
  // Pastes empleados salados
  {
    _id: "PES_A",
    saborDelPaste: "Atun",
    precio: 25,
    tipoDeProducto: "Paste Empleado Salado",
  },
  {
    _id: "PES_FCC",
    saborDelPaste: "Frijol con chorizo",
    precio: 25,
    tipoDeProducto: "Paste Empleado Salado",
  },
  {
    _id: "PES_H",
    saborDelPaste: "Hidalguense",
    precio: 25,
    tipoDeProducto: "Paste Empleado Salado",
  },
  {
    _id: "PES_M",
    saborDelPaste: "Marlin",
    precio: 25,
    tipoDeProducto: "Paste Empleado Salado",
  },
  {
    _id: "PES_MR",
    saborDelPaste: "Mole rojo",
    precio: 25,
    tipoDeProducto: "Paste Empleado Salado",
  },
  {
    _id: "PES_MV",
    saborDelPaste: "Mole Verde",
    precio: 25,
    tipoDeProducto: "Paste Empleado Salado",
  },
  {
    _id: "PES_PCC",
    saborDelPaste: "Papa con carne",
    precio: 25,
    tipoDeProducto: "Paste Empleado Salado",
  },
  {
    _id: "PES_PP",
    saborDelPaste: "Pepperoni",
    precio: 25,
    tipoDeProducto: "Paste Empleado Salado",
  },
  {
    _id: "PES_RCC",
    saborDelPaste: "Rajas con champiñon",
    precio: 25,
    tipoDeProducto: "Paste Empleado Salado",
  },
  {
    _id: "PES_ECR",
    saborDelPaste: "Espinacas con requeson",
    precio: 25,
    tipoDeProducto: "Paste Empleado Salado",
  },
  {
    _id: "PES_S",
    saborDelPaste: "Salchicha",
    precio: 25,
    tipoDeProducto: "Paste Empleado Salado",
  },
  {
    _id: "PES_TCP",
    saborDelPaste: "Tocino con papas",
    precio: 25,
    tipoDeProducto: "Paste Empleado Salado",
  },
  {
    _id: "PES_P",
    saborDelPaste: "Pastor",
    precio: 25,
    tipoDeProducto: "Paste Empleado Salado",
  },
  {
    _id: "PES_T",
    saborDelPaste: "Tapatio",
    precio: 25,
    tipoDeProducto: "Paste Empleado Salado",
  },
  {
    _id: "PES_C",
    saborDelPaste: "Choriqueso",
    precio: 25,
    tipoDeProducto: "Paste Empleado Salado",
  },
];
