export * from './candidato';
export * from './checkInPersonal';
export * from './clienteFrecuente';
export * from './manejoPersonal';
export * from './personalActivo';
export * from './productoYaComprado';
export * from './proveedor';
export * from './reporteDeCompra';
export * from './sucursalYFranquicia';